name: GreenLife-Project

services:
  backend:
    image: aytreasure/greenlife-backend:latest
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - ./greenlife_backend/.env
    volumes:
      - ./greenlife_backend/media:/app/media
      - ./greenlife_backend/staticfiles:/app/staticfiles
    networks:
      - app-network

  frontend:
    build:
      context: ./greenlife-frontend
      dockerfile: Dockerfile
      args:
        # Use Docker service name "backend" as the internal API host
        VITE_API_URL: http://backend:8000/api
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
