# Generated by Django 5.2.3 on 2025-06-28 19:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="treeentry",
            constraint=models.UniqueConstraint(
                fields=("user", "species", "location", "created_at"),
                name="unique_tree_per_user",
            ),
        ),
    ]
