# Generated by Django 5.2.3 on 2025-06-28 19:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0002_treeentry_unique_tree_per_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="treeentry",
            name="unique_tree_per_user",
        ),
        migrations.AddConstraint(
            model_name="treeentry",
            constraint=models.UniqueConstraint(
                fields=("user", "species", "location", "date_planted"),
                name="unique_tree_per_user",
            ),
        ),
    ]
