# Generated by Django 5.2.3 on 2025-06-28 20:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0003_remove_treeentry_unique_tree_per_user_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="treeentry",
            name="unique_tree_per_user",
        ),
        migrations.RemoveField(
            model_name="treeentry",
            name="location",
        ),
        migrations.AddField(
            model_name="treeentry",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="treeentry",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="treeentry",
            constraint=models.UniqueConstraint(
                fields=("user", "species", "latitude", "longitude", "date_planted"),
                name="unique_tree_per_user",
            ),
        ),
    ]
