# Generated by Django 5.2.3 on 2025-06-28 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0004_remove_treeentry_unique_tree_per_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="treeentry",
            name="latitude",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="treeentry",
            name="longitude",
            field=models.FloatField(),
        ),
    ]
