# Generated by Django 5.2.3 on 2025-06-28 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0005_alter_treeentry_latitude_alter_treeentry_longitude"),
    ]

    operations = [
        migrations.RenameField(
            model_name="treeentry",
            old_name="user",
            new_name="planter",
        ),
    ]
