# Generated by Django 5.2.3 on 2025-06-28 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0006_rename_user_treeentry_planter"),
    ]

    operations = [
        migrations.RenameField(
            model_name="treeentry",
            old_name="planter",
            new_name="user",
        ),
    ]
