# Azure Load Testing Configuration
testName: greenlife-load-test
description: Load test for GreenLife Eco Tracker application
engineInstances: 1

testPlan: locustfile.py

# Environment variables that will be passed to the test
env:
  - name: TARGET_URL
    value: "https://greenlife-tracker.greenplant-30488afa.southcentralus.azurecontainerapps.io"
  - name: USERS
    value: "50"
  - name: DURATION
    value: "300"
  - name: ENABLE_LOGGING
    value: "True"

# Load test configuration for Locust
configurationFiles:
  - locustfile.py

# Test criteria (auto-stop conditions)
autoStop:
  errorRate:
    percentage: 90
    timeWindow: 60
  responseTimeMs:
    value: 10000
    timeWindow: 60

# Test settings
failureCriteria:
  - aggregate: "percentage"
    metric: "error"
    operator: ">"
    value: 50
  - aggregate: "avg"
    metric: "response_time_ms"
    operator: ">"
    value: 5000

# Split traffic configuration
splitTraffic:
  enabled: false

# Monitoring configuration
monitoring:
  resourceIds: []

# Additional properties
properties:
  userPropertyAsString: "sample_property"
