name: Build and Push Docker Images

on:
    push:
        branches:
            - main

env:
    VM_IMAGE_NAME: ubuntu-latest
    ACR_SERVICE_CONNECTION: e671edeb-eee3-40aa-b2b8-2830eb2f8d37
    FRONTEND_DOCKERFILE: greenlife-frontend/Dockerfile
    FRONTEND_CONTEXT: greenlife-frontend
    FRONTEND_REPO: greenlifefront
    BACKEND_DOCKERFILE: greenlife_backend/Dockerfile
    BACKEND_CONTEXT: greenlife_backend
    BACKEND_REPO: greenlifeapi

jobs:
    build-and-push-backend:
        name: Build and Push Backend Image
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Log in to Azure Container Registry
              uses: azure/docker-login@v1
              with:
                  login-server: ${{ secrets.ACR_LOGIN_SERVER }}
                  username: ${{ secrets.ACR_USERNAME }}
                  password: ${{ secrets.ACR_PASSWORD }}

            - name: Build and Push Backend Docker Image
              run: |
                  docker build -t ${{ env.BACKEND_REPO }}:${{ github.run_number }} -f ${{ env.BACKEND_DOCKERFILE }} ${{ env.BACKEND_CONTEXT }}
                  docker build -t ${{ env.BACKEND_REPO }}:latest -f ${{ env.BACKEND_DOCKERFILE }} ${{ env.BACKEND_CONTEXT }}
                  docker tag ${{ env.BACKEND_REPO }}:${{ github.run_number }} ${{ secrets.ACR_LOGIN_SERVER }}/${{ env.BACKEND_REPO }}:${{ github.run_number }}
                  docker tag ${{ env.BACKEND_REPO }}:latest ${{ secrets.ACR_LOGIN_SERVER }}/${{ env.BACKEND_REPO }}:latest
                  docker push ${{ secrets.ACR_LOGIN_SERVER }}/${{ env.BACKEND_REPO }}:${{ github.run_number }}
                  docker push ${{ secrets.ACR_LOGIN_SERVER }}/${{ env.BACKEND_REPO }}:latest

    build-and-push-frontend:
        name: Build and Push Frontend Image
        runs-on: ubuntu-latest
        needs: build-and-push-backend
        steps:
            - uses: actions/checkout@v3

            - name: Log in to Azure Container Registry
              uses: azure/docker-login@v1
              with:
                  login-server: ${{ secrets.ACR_LOGIN_SERVER }}
                  username: ${{ secrets.ACR_USERNAME }}
                  password: ${{ secrets.ACR_PASSWORD }}

            - name: Build and Push Frontend Docker Image
              run: |
                  docker build -t ${{ env.FRONTEND_REPO }}:${{ github.run_number }} -f ${{ env.FRONTEND_DOCKERFILE }} ${{ env.FRONTEND_CONTEXT }}
                  docker build -t ${{ env.FRONTEND_REPO }}:latest -f ${{ env.FRONTEND_DOCKERFILE }} ${{ env.FRONTEND_CONTEXT }}
                  docker tag ${{ env.FRONTEND_REPO }}:${{ github.run_number }} ${{ secrets.ACR_LOGIN_SERVER }}/${{ env.FRONTEND_REPO }}:${{ github.run_number }}
                  docker tag ${{ env.FRONTEND_REPO }}:latest ${{ secrets.ACR_LOGIN_SERVER }}/${{ env.FRONTEND_REPO }}:latest
                  docker push ${{ secrets.ACR_LOGIN_SERVER }}/${{ env.FRONTEND_REPO }}:${{ github.run_number }}
                  docker push ${{ secrets.ACR_LOGIN_SERVER }}/${{ env.FRONTEND_REPO }}:latest
