# Auto Load Testing on Push

name: Load Testing

on:
  push:
    branches:
      - main
      - develop

jobs:
  load-test:
    runs-on: ubuntu-latest

    env:
      USERS: 50
      DURATION: 300

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Azure CLI and dependencies
      run: |
        pip install locust requests python-dotenv
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
        az extension add --name load

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Determine environment and set variables
      run: |
        if [[ "${GITHUB_REF##*/}" == "main" ]]; then
          echo "ENVIRONMENT=production" >> $GITHUB_ENV
          echo "LOAD_TEST_RESOURCE=greenlife-load-test-prod-81jg" >> $GITHUB_ENV
          echo "RESOURCE_GROUP=Greenlifebackend_group-prod" >> $GITHUB_ENV
          echo "HOST=https://greenlife-tracker-prod.greenplant-30488afa.southcentralus.azurecontainerapps.io" >> $GITHUB_ENV
        elif [[ "${GITHUB_REF##*/}" == "develop" ]]; then
          echo "ENVIRONMENT=staging" >> $GITHUB_ENV
          echo "LOAD_TEST_RESOURCE=greenlife-load-test-staging-91ha" >> $GITHUB_ENV
          echo "RESOURCE_GROUP=Greenlifebackend_group-a7e3" >> $GITHUB_ENV
          echo "HOST=https://greenlife-tracker.greenplant-30488afa.southcentralus.azurecontainerapps.io" >> $GITHUB_ENV
        else
          echo "ENVIRONMENT=web" >> $GITHUB_ENV
          echo "LOAD_TEST_RESOURCE=greenlife-load-test-web" >> $GITHUB_ENV
          echo "RESOURCE_GROUP=Greenlifefrontend_group" >> $GITHUB_ENV
          echo "HOST=https://greengoal.azurewebsites.net" >> $GITHUB_ENV
        fi

    - name: Run Azure Load Test
      run: |
        cd load_tests
        # Generate unique test ID
        TEST_ID="ci-load-test-$(date +%Y%m%d-%H%M%S)"
        echo "Creating load test with ID: $TEST_ID"
        # Create the load test
        az load test create \
          --test-id "$TEST_ID" \
          --resource-group $RESOURCE_GROUP \
          --load-test-resource $LOAD_TEST_RESOURCE \
          --display-name "CI Load Test $(date)" \
          --description "Automated load test from GitHub Actions" \
          --test-plan locustfile.py \
          --env TARGET_URL="$HOST" USERS="$USERS" DURATION="$DURATION" ENABLE_LOGGING="False"

        if [ $? -ne 0 ]; then
          echo "Failed to create load test"
          exit 1
        fi

        echo "TEST_ID=$TEST_ID" >> $GITHUB_ENV
        echo "Load test created with ID: $TEST_ID"

        # Start the test run
        echo "Starting load test run..."
        RUN_ID=$(az load test-run create \
          --test-id "$TEST_ID" \
          --resource-group $RESOURCE_GROUP \
          --load-test-resource $LOAD_TEST_RESOURCE \
          --display-name "CI Run $(date)" \
          --query "testRunId" -o tsv)

        if [ -z "$RUN_ID" ]; then
          echo "Failed to start test run"
          exit 1
        fi

        echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
        echo "Test run started with ID: $RUN_ID"

        # Wait for test to complete (with timeout)
        echo "Waiting for test completion..."
        timeout 900 bash -c 'while [[ $(az load test-run show --test-run-id '$RUN_ID' --resource-group '$RESOURCE_GROUP' --load-test-resource '$LOAD_TEST_RESOURCE' --query "status" -o tsv) != "DONE" ]]; do echo "Test in progress..."; sleep 30; done'

    - name: Download Test Results
      run: |
        # Download test results
        echo "Downloading test results for run ID: $RUN_ID"
        az load test-run download-files \
          --test-run-id $RUN_ID \
          --resource-group $RESOURCE_GROUP \
          --load-test-resource $LOAD_TEST_RESOURCE \
          --path ./test-results

        # Show test results summary
        echo "Test results summary:"
        az load test-run show \
          --test-run-id $RUN_ID \
          --resource-group $RESOURCE_GROUP \
          --load-test-resource $LOAD_TEST_RESOURCE \
          --query "{status: status, startDateTime: startDateTime, endDateTime: endDateTime}" -o table

    - name: Upload Azure Load Test Results
      uses: actions/upload-artifact@v4
      env:
        ENVIRONMENT: ${{ env.ENVIRONMENT }}
      with:
        name: azure-load-test-results-${{ env.ENVIRONMENT }}
        path: |
          ./test-results/
          load_tests/locustfile.py