# .github/workflows/release.yml
name: Releases

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Semantic Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # important for changelog and version diff

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install dependencies
        working-directory: ./greenlife-frontend
        run: npm ci

      - name: Run semantic-release
        working-directory: ./greenlife-frontend
        env:
          GITHUB_TOKEN: ${{ secrets.MANUAL_APPROVAL_TOKEN }}
        run: npx semantic-release
